### ISSUE TITLE
Fail to load plugin

### ISSUE THREAD

**Issue by NetanelBasal** [andresdominguez/elementor-idea#1]
I downloaded the jar file and follow the instructions but when i am trying to load the plugin i get this error:

`Fail to load plugin descriptor from file element-idea.jar`

**Comment by reiaguilera** [comment]
Hi @NetanelBasal You can download directly from IDE> plugins> browse repositories>elementor :trollface:

**Comment by piotrd** [comment]
@andresdominguez: an update to README would be helpful with the above.

**Comment by andresdominguez** [comment]
I updated the README file. Thank you for letting me know
